# [environments.production.build]
# builder = "nixpacks"
# buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader && npm install && npm run prod && php artisan optimize && php artisan config:cache && php artisan route:cache && php artisan view:cache"

# [environments.production.deploy]
# startCommand = "php artisan migrate --force"
# replicas = 1
# healthcheckPath = "/"
# healthcheckTimeout = 100
# restartPolicyType = "on_failure"
# maxRestartRetries = 10